INSERT INTO users (
    id,
    name,
    description,
    date_of_birth,
    email,
    password_hash,
    email_verified,
    verification_token,
    token_expiry_date,
    phone_number,
    profile_picture_url,
    gender,
    role,
    last_login,
    time_zone,
    account_status,
    row_created_on,
    row_updated_on
) VALUES
      (
          '650e8400-e29b-41d4-a716-446655440010',
          'Unverified User',
          'User with unverified email - can resend',
          '1995-03-25',
          'unverified@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
          false,
          'old-verification-token',
          NOW() + INTERVAL '1 day',
          '+5566778899',
          NULL,
          'female',
          'user',
          NULL,
          'UTC',
          'active',
          NOW(),
          NOW() - INTERVAL '3 minutes'
      ),
      (
          '650e8400-e29b-41d4-a716-446655440011',
          'Verified User',
          'User with already verified email',
          '1990-08-15',
          'verified@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
          true,
          NULL,
          NULL,
          '+1122334455',
          NULL,
          'male',
          'user',
          NOW(),
          'UTC',
          'active',
          NOW(),
          NOW()
      ),
      (
          '650e8400-e29b-41d4-a716-446655440012',
          'Recent Email User',
          'User who requested email recently - within 2 minutes',
          '1992-06-10',
          'recent@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
          false,
          'recent-verification-token',
          NOW() + INTERVAL '1 day',
          '+9988776655',
          NULL,
          'male',
          'user',
          NULL,
          'UTC',
          'active',
          NOW(),
          NOW()
      );