INSERT INTO users (
    id,
    name,
    description,
    date_of_birth,
    email,
    password_hash,
    email_verified,
    verification_token,
    token_expiry_date,
    phone_number,
    profile_picture_url,
    gender,
    role,
    last_login,
    time_zone,
    account_status,
    row_created_on,
    row_updated_on
) VALUES
      (
          '550e8400-e29b-41d4-a716-446655440000',
          'John Doe',
          'Test user account',
          '1990-01-15',
          'test@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- password: password
          true,
          NULL,
          NULL,
          '+1234567890',
          'https://example.com/profile.jpg',
          'male',
          'user',
          NOW(),
          'UTC',
          'active',
          NOW(),
          NOW()
      ),
      (
          '550e8400-e29b-41d4-a716-446655440001',
          'Jane Smith',
          'Another test user',
          '1992-05-20',
          'user2@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- password: password
          true,
          NULL,
          NULL,
          '+0987654321',
          'https://example.com/jane.jpg',
          'female',
          'user',
          NOW(),
          'UTC',
          'active',
          NOW(),
          NOW()
      ),
      (
          '550e8400-e29b-41d4-a716-446655440002',
          'Admin User',
          'Administrator account',
          '1985-12-10',
          'admin@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- password: password
          true,
          NULL,
          NULL,
          '+1122334455',
          'https://example.com/admin.jpg',
          'male',
          'admin',
          NOW(),
          'UTC',
          'active',
          NOW(),
          NOW()
      ),
      (
          '550e8400-e29b-41d4-a716-446655440003',
          'Inactive User',
          'Inactive test account',
          '1995-03-25',
          'inactive@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- password: password
          false,
          'verification-token-123',
          NOW() + INTERVAL '1 day',
          '+5566778899',
          NULL,
          'female',
          'user',
          NULL,
          'UTC',
          'inactive',
          NOW(),
          NOW()
      ),
      (
          '550e8400-e29b-41d4-a716-446655440004',
          'Error User',
          'User for error testing',
          '1988-07-30',
          'error@example.com',
          '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- password: password
          true,
          NULL,
          NULL,
          '+9988776655',
          NULL,
          'male',
          'user',
          NOW(),
          'UTC',
          'active',
          NOW(),
          NOW()
      );